name: daily-report

on:
  schedule:
    - cron: '10 22 * * *'  # 07:10 JST daily
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: daily-report
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate Top10 JSON
        env:
          TIINGO_TOKEN: ${{ secrets.TIINGO_TOKEN }}
          REPORT_DATE: ${{ vars.REPORT_DATE }}
          MOCK_MODE: ${{ vars.MOCK_MODE || 'true' }}   # ← 初期はtrueでOK
          BUDGET_JPY_MAX: ${{ vars.BUDGET_JPY_MAX || '10000' }}
          MANUAL_DAILY_COST_JPY: ${{ vars.MANUAL_DAILY_COST_JPY || '0' }}
          TIINGO_MONTHLY_JPY: ${{ vars.TIINGO_MONTHLY_JPY || '1600' }}
        run: |
          python scripts/fetch_daily.py
      - name: Render HTML
        run: |
          python scripts/render.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "chore: publish daily report" || echo "no changes"
          git push
