name: daily-report

on:
  schedule:
    - cron: '10 22 * * *'  # 18:10 ET / 07:10 JST 相当
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: daily-report
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Top10 JSON
        env:
          TIINGO_TOKEN: ${{ secrets.TIINGO_TOKEN }}
          REPORT_DATE: ${{ vars.REPORT_DATE }}
          MOCK_MODE: ${{ vars.MOCK_MODE || 'true' }}
          BUDGET_JPY_MAX: ${{ vars.BUDGET_JPY_MAX || '10000' }}
          MANUAL_DAILY_COST_JPY: ${{ vars.MANUAL_DAILY_COST_JPY || '0' }}
          TIINGO_MONTHLY_JPY: ${{ vars.TIINGO_MONTHLY_JPY || '1600' }}
          DATA_PROVIDER: ${{ vars.DATA_PROVIDER || 'yfinance' }}
        run: python scripts/fetch_daily.py

      - name: Render HTML
        run: python scripts/render.py

      - name: Verify outputs (ET market date)
        shell: bash
        run: |
          echo "REPORT_DATE=${{ vars.REPORT_DATE }}"
          ls -la site/daily || true

          DATE_TO_CHECK="${{ vars.REPORT_DATE }}"
          if [ -z "$DATE_TO_CHECK" ]; then
            DATE_TO_CHECK=$(python scripts/et_market_date.py)
          fi

          echo "Checking file: site/daily/${DATE_TO_CHECK}.html"
          test -f "site/daily/${DATE_TO_CHECK}.html" || (echo "Expected file missing: site/daily/${DATE_TO_CHECK}.html" && exit 1)
          
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "chore: publish daily report" || echo "no changes"
          git push
      - name: Fetch Form 4 (insider momentum)
        env:
          OUT_DIR: site
          UNIVERSE_CSV: data/universe.csv
          REPORT_DATE: ${{ steps.set_date.outputs.REPORT_DATE }}   # 既存のやり方に合わせてください
          SEC_USER_AGENT: "futuretech-stock/1.0 (sachiohiro777@gmail.com)"
          FORM4_MAX_FILINGS: "10"         # 大企業でも十分
          FORM4_MAX_AGE_DAYS: "95"        # ここより古い提出は打ち切り
          SEC_SLEEP: "0.7"                # 会社ごとの小休止
          SEC_XML_SLEEP: "0.25"           # XML 取得の小休止
          SEC_RETRY: "3"
        run: |
          python scripts/fetch_form4.py

      - name: Generate daily ranking
        env:
          DATA_PROVIDER: yfinance
          MOCK_MODE: "false"
          OUT_DIR: site
          UNIVERSE_CSV: data/universe.csv
          REPORT_DATE: ${{ steps.set_date.outputs.REPORT_DATE }}
          WEIGHT_VOL_ANOM: "0.60"
          WEIGHT_FORM4: "0.40"               # ← 重み調整はここで
          FORM4_JSON: site/data/insider/form4_latest.json
        run: |
          python scripts/fetch_daily.py
