name: fetch-news

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと（必要なら変更）
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch news (idempotent)
        env:
          OUT_DIR: site
          UNIVERSE_CSV: data/universe.csv
          NEWS_USER_AGENT: "futuretech-stock/1.0 (news-fetcher)"
          NEWS_SLEEP: "1.2"
          NEWS_JITTER: "0.8"
          NEWS_DAYS_KEEP: "45"
          NEWS_RECENT_DAYS: "3"
          NEWS_LOOKBACK_DAYS: "31"
          NEWS_MAX_PER_SYMBOL: "60"
        run: |
          python scripts/fetch_news.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "chore: update news cache" || echo "no changes"
          git push
